# Generated by Django 3.1.2 on 2020-10-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201020_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messaage',
        ),
    ]
